version: '3.5'

services:
  purbalingga-memikat:
    container_name: "purbalingga-memikat"
    image: postgres
    ports:
      - 5454:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: purbalingga-memikat